import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/Navbar";

import { Providers } from "./providers";
import { PolybaseParent } from "./polybaseprovider";
import Footer from "@/components/Footer";
import { CheckAccount } from "@/providers/checkAccount";
import "@rainbow-me/rainbowkit/styles.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light" style={{ height: "100%" }}>
			<body
				className={inter.className}
				style={{
					height: "100%",
					margin: 0,
					display: "flex",
					flexDirection: "column",
				}}
			>
				<PolybaseParent style={{ flex: 1 }}>
					<Providers>
						<CheckAccount>
							<Navbar />
							<div style={{ flex: 1 }}>{children}</div>
							{/* <Footer /> */}
						</CheckAccount>
					</Providers>
				</PolybaseParent>
			</body>
		</html>
	);
}
